SELECT
EXTRACT(MONTH FROM order_date) AS order_year,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) AS total_customers,
SUM(quantity) AS total_quantity
FROM gold_fact_sales
WHERE order_date IS NOT NULL
GROUP BY EXTRACT(MONTH FROM order_date)
ORDER BY EXTRACT(MONTH FROM order_date)

-- MEASURE EXPLORATION
-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold_fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold_fact_sales

-- Find the Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold_fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold_fact_sales

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold_dim_customers

-- Find the total number of customers that has placed and order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold_fact_sales

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold_fact_sales
UNION ALL
SELECT 'Total Quantity' , SUM(quantity)  FROM gold_fact_sales
UNION ALL
SELECT 'Average Price' , AVG(price) FROM gold_fact_sales
UNION ALL
SELECT 'Total no. Orders' , COUNT(DISTINCT order_number) FROM gold_fact_sales
UNION ALL
SELECT 'Total no. Products' , COUNT(product_name) FROM gold_dim_products
UNION ALL
SELECT 'Total no. Customers' , COUNT(customer_key) FROM gold_dim_customers


-- Dimention exploration
-- Find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold_dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold_dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT * FROM gold_dim_products
SELECT 
category,
COUNT(product_number) AS total_products
FROM gold_dim_products
GROUP BY category
ORDER BY total_products DESC

-- Average Cost in Each Category
SELECT
category,
ROUND(AVG(cost)) AS Avg_cost
FROM gold_dim_products
GROUP BY category
ORDER BY Avg_cost DESC

-- Total Revenue generated by each category
SELECT 
p.category,
SUM(s.sales_amount) AS Total_Revenue
FROM gold_fact_sales AS s 
LEFT JOIN gold_dim_products as p
ON p.product_key = s.product_key
GROUP BY p.category

-- Find Total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS Total_Revenue
FROM gold_fact_sales s
LEFT JOIN gold_dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Revenue DESC


-- What is the distribution of sold items across countries?

SELECT 
c.country,
SUM(s.quantity) AS Total_Sold_Items
FROM gold_fact_sales s
LEFT JOIN gold_dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.country
ORDER BY Total_Sold_Items DESC

-- RANKING ANALYSIS
--- Which 5 products generate the highest revenue?
SELECT
p.product_name,
p.category,
SUM(s.sales_amount) AS Total_revenue
FROM gold_fact_sales s
LEFT JOIN gold_dim_products p
ON s.product_key = p.product_key
GROUP BY 
p.product_name,
p.category
ORDER BY Total_revenue DESC
LIMIT 5

--Using rank function
SELECT * 
FROM (
     SELECT
	 p.product_name,
	 SUM(s.sales_amount) total_revenue,
	 ROW_NUMBER() OVER (ORDER BY SUM(s.sales_amount) DESC) AS rank_products
	 FROM gold_fact_sales s
	 LEFT JOIN gold_dim_products p
	 ON p.product_key = s.product_key
	 GROUP BY p.product_name) t
WHERE rank_products <= 5


-- WHAT ARE the 5 worst-performing products in terms of sales?
SELECT
p.product_name,
p.category,
SUM(s.sales_amount) AS Total_revenue
FROM gold_fact_sales s
LEFT JOIN gold_dim_products p
ON s.product_key = p.product_key
GROUP BY 
p.product_name,
p.category
ORDER BY Total_revenue ASC
LIMIT 5

-- WHich are top 10 customers who have generated highest revenue
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS Total_Revenue
FROM gold_fact_sales s
LEFT JOIN gold_dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Revenue DESC
LIMIT 10

-- Customers who have least order
SELECT 
c.customer_key,
c.first_name,
c.last_name,
Count(DISTINCT s.order_number) AS Total_Orders
FROM gold_fact_sales s
LEFT JOIN gold_dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Orders ASC
LIMIT 5

--Top 3 BEST performing product in each category

WITH ranked_products AS (
    SELECT
        p.category,
        p.product_name,
        SUM(s.sales_amount) AS total_sales,
        ROW_NUMBER() OVER (
            PARTITION BY p.category 
            ORDER BY SUM(s.sales_amount) DESC
        ) AS sales_rank
    FROM gold_fact_sales s   
    LEFT JOIN gold_dim_products p
        ON s.product_key = p.product_key
    GROUP BY p.category, p.product_name
)
SELECT
    category,
    product_name,
    total_sales,
	sales_rank
FROM ranked_products
WHERE sales_rank IN (1,2,3)
ORDER BY category;

--Top 3 worst performing product in each category in terms of revenue

WITH ranked_products AS (
    SELECT
        p.category,
        p.product_name,
        SUM(s.sales_amount) AS total_sales,
        ROW_NUMBER() OVER (
            PARTITION BY p.category 
            ORDER BY SUM(s.sales_amount) ASC
        ) AS sales_rank
    FROM gold_fact_sales s   
    LEFT JOIN gold_dim_products p
        ON s.product_key = p.product_key
    GROUP BY p.category, p.product_name
)
SELECT
    category,
    product_name,
    total_sales,
	sales_rank
FROM ranked_products
WHERE sales_rank IN (1,2,3)
ORDER BY category;


-- Most Popular products by country and quantity
WITH country_performance AS (
	SELECT 
		c.country AS country,
		p.category AS category,
		p.product_name AS product_name,
		SUM(s.quantity) Total_qty_orderd, 
		ROW_NUMBER() OVER(
			PARTITION BY c.country, p.category
			ORDER BY SUM(s.quantity) DESC
		) AS quantity_rank
	FROM gold_fact_sales s
	LEFT JOIN gold_dim_products p 
		ON s.product_key = p.product_key
	LEFT JOIN gold_dim_customers c
		ON s.customer_key = c.customer_key
    GROUP BY p.category, p.product_name, c.country
)
SELECT
	 country,
	 category,
	 product_name,
	 Total_qty_orderd
FROM country_performance
WHERE quantity_rank = 1
























































































































